const NAME_OR_PASSWORD_IS_NOT_NULL = '用户名或者密码不能为空~'
const USER_ALREADY_EXISTS = '该用户名已经存在~'
const USER_DOES_NOT_EXIST = '用户名不存在~'
const WRONG_PASSWORD = '密码错误~'
const UNAUTHORIZED = '未授权~'
const NONEXISTENT_TOKEN = '不存在的token~'
const UNPREMISSION = '您不具备操作的权限~'

module.exports = {
  NAME_OR_PASSWORD_IS_NOT_NULL,
  USER_ALREADY_EXISTS,
  USER_DOES_NOT_EXIST,
  WRONG_PASSWORD,
  UNAUTHORIZED,
  NONEXISTENT_TOKEN,
  UNPREMISSION,
}
